// Code generated by scripts/fill-integration-coverage.sh; DO NOT EDIT.
//
// This bridge re-executes the package's existing scenario tests during
// the independent integration-coverage pass without changing production code.
package control

import "testing"

func TestIntegrationCoverageBridge(t *testing.T) {
	tests := []struct {
		name string
		run  func(*testing.T)
	}{
		{name: "TestAuthorizationComparisonUsesFixedLengthDigests", run: TestAuthorizationComparisonUsesFixedLengthDigests},
		{name: "TestControlValidationHelpersCoverBoundaries", run: TestControlValidationHelpersCoverBoundaries},
		{name: "TestDecodeJSONRejectsStreamingOversize", run: TestDecodeJSONRejectsStreamingOversize},
		{name: "TestHandlerAuditsMethodAndRouteRejections", run: TestHandlerAuditsMethodAndRouteRejections},
		{name: "TestHandlerAuditsStoreFailureWithoutExposingDetails", run: TestHandlerAuditsStoreFailureWithoutExposingDetails},
		{name: "TestHandlerBuildsUnknownAndBoundedAuditCaller", run: TestHandlerBuildsUnknownAndBoundedAuditCaller},
		{name: "TestHandlerHandlesRejectedAuditFailure", run: TestHandlerHandlesRejectedAuditFailure},
		{name: "TestHandlerHealthAndSecurityHeaders", run: TestHandlerHealthAndSecurityHeaders},
		{name: "TestHandlerRejectsEveryMutationValidationPath", run: TestHandlerRejectsEveryMutationValidationPath},
		{name: "TestHandlerRejectsMalformedAuthenticatedAttemptsAndAudits", run: TestHandlerRejectsMalformedAuthenticatedAttemptsAndAudits},
		{name: "TestHandlerRequiresIndependentOperatorAuthorization", run: TestHandlerRequiresIndependentOperatorAuthorization},
		{name: "TestHandlerRoutesAllMutations", run: TestHandlerRoutesAllMutations},
		{name: "TestNewHandlerValidatesDependenciesAndToken", run: TestNewHandlerValidatesDependenciesAndToken},
	}

	for _, test := range tests {
		t.Run(test.name, test.run)
	}
}
