// Code generated by scripts/fill-integration-coverage.sh; DO NOT EDIT.
//
// This bridge re-executes the package's existing scenario tests during
// the independent integration-coverage pass without changing production code.
package declaration

import "testing"

func TestIntegrationCoverageBridge(t *testing.T) {
	tests := []struct {
		name string
		run  func(*testing.T)
	}{
		{name: "TestParseEnforcesBodyLimit", run: TestParseEnforcesBodyLimit},
		{name: "TestParseMinimumDeclaration", run: TestParseMinimumDeclaration},
		{name: "TestParseRejectsDuplicateMemberNames", run: TestParseRejectsDuplicateMemberNames},
		{name: "TestParseRejectsExcessiveNesting", run: TestParseRejectsExcessiveNesting},
		{name: "TestParseRejectsInvalidDeclarations", run: TestParseRejectsInvalidDeclarations},
		{name: "TestParseReportsUnsupportedVersions", run: TestParseReportsUnsupportedVersions},
		{name: "TestParseValidDeclarations", run: TestParseValidDeclarations},
		{name: "TestReadDeclarationBodyAcceptsExactLimit", run: TestReadDeclarationBodyAcceptsExactLimit},
		{name: "TestReadDeclarationBodyRejectsNilBody", run: TestReadDeclarationBodyRejectsNilBody},
		{name: "TestReadDeclarationBodyRejectsOversizeWithoutOverreading", run: TestReadDeclarationBodyRejectsOversizeWithoutOverreading},
		{name: "TestReadDeclarationBodyReturnsReadFailure", run: TestReadDeclarationBodyReturnsReadFailure},
		{name: "TestVerifierClassifiesHTTPOutcomes", run: TestVerifierClassifiesHTTPOutcomes},
		{name: "TestVerifierDistinguishesRobotsDenial", run: TestVerifierDistinguishesRobotsDenial},
		{name: "TestVerifierFollowsFiveSameOriginRedirects", run: TestVerifierFollowsFiveSameOriginRedirects},
		{name: "TestVerifierFollowsSameOriginRedirects", run: TestVerifierFollowsSameOriginRedirects},
		{name: "TestVerifierHandlesDeclarationBodyFailures", run: TestVerifierHandlesDeclarationBodyFailures},
		{name: "TestVerifierPreservesContextCancellation", run: TestVerifierPreservesContextCancellation},
		{name: "TestVerifierPreservesTypedTransientHTTPRetryMetadata", run: TestVerifierPreservesTypedTransientHTTPRetryMetadata},
		{name: "TestVerifierRejectsCrossOriginRedirects", run: TestVerifierRejectsCrossOriginRedirects},
		{name: "TestVerifierRejectsInvalidInputs", run: TestVerifierRejectsInvalidInputs},
		{name: "TestVerifierRejectsMissingInjectedClock", run: TestVerifierRejectsMissingInjectedClock},
		{name: "TestVerifierRejectsRedirectFailures", run: TestVerifierRejectsRedirectFailures},
		{name: "TestVerifierRetrievesCanonicalDeclarationTarget", run: TestVerifierRetrievesCanonicalDeclarationTarget},
		{name: "TestVerifierUsesInjectedClockForDateRetryAfter", run: TestVerifierUsesInjectedClockForDateRetryAfter},
	}

	for _, test := range tests {
		t.Run(test.name, test.run)
	}
}
