// Code generated by scripts/fill-integration-coverage.sh; DO NOT EDIT.
//
// This bridge re-executes the package's existing scenario tests during
// the independent integration-coverage pass without changing production code.
package robots

import "testing"

func TestIntegrationCoverageBridge(t *testing.T) {
	tests := []struct {
		name string
		run  func(*testing.T)
	}{
		{name: "TestCheckerCachesByInitialOriginFor24Hours", run: TestCheckerCachesByInitialOriginFor24Hours},
		{name: "TestCheckerCoalescesConcurrentCacheMisses", run: TestCheckerCoalescesConcurrentCacheMisses},
		{name: "TestCheckerDoesNotCacheFailureOrReviveStalePolicy", run: TestCheckerDoesNotCacheFailureOrReviveStalePolicy},
		{name: "TestCheckerEnforcesEffectivePerOriginRequestDelay", run: TestCheckerEnforcesEffectivePerOriginRequestDelay},
		{name: "TestCheckerGetEnforcesPolicy", run: TestCheckerGetEnforcesPolicy},
		{name: "TestCheckerGetFailsClosed", run: TestCheckerGetFailsClosed},
		{name: "TestCheckerGetUsesJoshBotIdentityForRobotsAndTarget", run: TestCheckerGetUsesJoshBotIdentityForRobotsAndTarget},
		{name: "TestCheckerRejectsInvalidInputs", run: TestCheckerRejectsInvalidInputs},
		{name: "TestCheckerRejectsMalformedApplicableCrawlDelay", run: TestCheckerRejectsMalformedApplicableCrawlDelay},
		{name: "TestCheckerSchedulesSameOriginRobotsRedirect", run: TestCheckerSchedulesSameOriginRobotsRedirect},
		{name: "TestCheckerSignsRobotsRedirectsAndProtectedRequests", run: TestCheckerSignsRobotsRedirectsAndProtectedRequests},
		{name: "TestCheckerSignsScheduledRobotsAndProtectedRequests", run: TestCheckerSignsScheduledRobotsAndProtectedRequests},
		{name: "TestCheckerUsesIndependentDestinationOriginSchedule", run: TestCheckerUsesIndependentDestinationOriginSchedule},
		{name: "TestGuardedHTTPPreservesIdentityAndTLSAuthority", run: TestGuardedHTTPPreservesIdentityAndTLSAuthority},
		{name: "TestGuardedHTTPRejectsInvalidInputs", run: TestGuardedHTTPRejectsInvalidInputs},
		{name: "TestGuardedHTTPRejectsUnsafeAddressBeforeDial", run: TestGuardedHTTPRejectsUnsafeAddressBeforeDial},
		{name: "TestGuardedHTTPRejectsUnsafeRedirectBeforeDial", run: TestGuardedHTTPRejectsUnsafeRedirectBeforeDial},
		{name: "TestGuardedHTTPRejectsUntrustedTLS", run: TestGuardedHTTPRejectsUntrustedTLS},
		{name: "TestGuardedHTTPReturnsContextErrorFromFailedRequest", run: TestGuardedHTTPReturnsContextErrorFromFailedRequest},
		{name: "TestGuardedHTTPStopsBeforeDialWhenSigningFails", run: TestGuardedHTTPStopsBeforeDialWhenSigningFails},
		{name: "TestGuardedTransportDisablesProxyAndTLSBypass", run: TestGuardedTransportDisablesProxyAndTLSBypass},
		{name: "TestIdentityIsStableAndTransparent", run: TestIdentityIsStableAndTransparent},
		{name: "TestObtainPolicyFollowsRedirects", run: TestObtainPolicyFollowsRedirects},
		{name: "TestObtainPolicyInterpretsHTTPResults", run: TestObtainPolicyInterpretsHTTPResults},
		{name: "TestObtainPolicyRejectsInvalidInputs", run: TestObtainPolicyRejectsInvalidInputs},
		{name: "TestObtainPolicyRejectsRedirectFailures", run: TestObtainPolicyRejectsRedirectFailures},
		{name: "TestObtainPolicyReturnsContextErrorFromFailedFetch", run: TestObtainPolicyReturnsContextErrorFromFailedFetch},
		{name: "TestOriginRequestSchedulerRejectsInvalidTargetsAndDelay", run: TestOriginRequestSchedulerRejectsInvalidTargetsAndDelay},
		{name: "TestOriginRequestSchedulerUsesActualRequestStart", run: TestOriginRequestSchedulerUsesActualRequestStart},
		{name: "TestParseUsesParseableRecords", run: TestParseUsesParseableRecords},
		{name: "TestPatternMatchesAdversarialWildcardInput", run: TestPatternMatchesAdversarialWildcardInput},
		{name: "TestPolicyCrawlDelayDoesNotChangeAllowDisallow", run: TestPolicyCrawlDelayDoesNotChangeAllowDisallow},
		{name: "TestPolicyCrawlDelayRejectsMalformedValues", run: TestPolicyCrawlDelayRejectsMalformedValues},
		{name: "TestPolicyCrawlDelayRepeatedDirectives", run: TestPolicyCrawlDelayRepeatedDirectives},
		{name: "TestPolicyCrawlDelaySelection", run: TestPolicyCrawlDelaySelection},
		{name: "TestPolicyDisallowsJoshBotPath", run: TestPolicyDisallowsJoshBotPath},
		{name: "TestPolicyMatchesTargetURI", run: TestPolicyMatchesTargetURI},
		{name: "TestPolicyRejectsInvalidTarget", run: TestPolicyRejectsInvalidTarget},
		{name: "TestPolicySelectsJoshBotGroups", run: TestPolicySelectsJoshBotGroups},
		{name: "TestReadPolicyAcceptsExactBodyLimit", run: TestReadPolicyAcceptsExactBodyLimit},
		{name: "TestReadPolicyFailsClosedOnReadError", run: TestReadPolicyFailsClosedOnReadError},
		{name: "TestReadPolicyFailsClosedWithoutBody", run: TestReadPolicyFailsClosedWithoutBody},
		{name: "TestReadPolicyRejectsOversizedBodyWithoutOverreading", run: TestReadPolicyRejectsOversizedBodyWithoutOverreading},
		{name: "TestScheduledHopGetterStopsWhenWaitFails", run: TestScheduledHopGetterStopsWhenWaitFails},
		{name: "TestTimerRequestDelayWaiter", run: TestTimerRequestDelayWaiter},
	}

	for _, test := range tests {
		t.Run(test.name, test.run)
	}
}
