// Code generated by scripts/fill-integration-coverage.sh; DO NOT EDIT.
//
// This bridge re-executes the package's existing scenario tests during
// the independent integration-coverage pass without changing production code.
package githubpublish

import "testing"

func TestIntegrationCoverageBridge(t *testing.T) {
	tests := []struct {
		name string
		run  func(*testing.T)
	}{
		{name: "TestPublisherHandlesGitHubStatusFailuresSafely", run: TestPublisherHandlesGitHubStatusFailuresSafely},
		{name: "TestPublisherInternalValidationBoundaries", run: TestPublisherInternalValidationBoundaries},
		{name: "TestPublisherNewConstructsPublisher", run: TestPublisherNewConstructsPublisher},
		{name: "TestPublisherPreservesContextCancellation", run: TestPublisherPreservesContextCancellation},
		{name: "TestPublisherPropagatesEveryPublicationStageFailure", run: TestPublisherPropagatesEveryPublicationStageFailure},
		{name: "TestPublisherPropagatesReconciliationReadFailures", run: TestPublisherPropagatesReconciliationReadFailures},
		{name: "TestPublisherPublishesExactChangedSnapshot", run: TestPublisherPublishesExactChangedSnapshot},
		{name: "TestPublisherReconcilesConcurrentSameTree", run: TestPublisherReconcilesConcurrentSameTree},
		{name: "TestPublisherRejectsAuthenticatedRedirect", run: TestPublisherRejectsAuthenticatedRedirect},
		{name: "TestPublisherRejectsInvalidConfiguration", run: TestPublisherRejectsInvalidConfiguration},
		{name: "TestPublisherRejectsInvalidPublisher", run: TestPublisherRejectsInvalidPublisher},
		{name: "TestPublisherRejectsInvalidSnapshotBeforeNetwork", run: TestPublisherRejectsInvalidSnapshotBeforeNetwork},
		{name: "TestPublisherRejectsInvalidSuccessfulResponses", run: TestPublisherRejectsInvalidSuccessfulResponses},
		{name: "TestPublisherRejectsInvalidTokenAndTestAPIBase", run: TestPublisherRejectsInvalidTokenAndTestAPIBase},
		{name: "TestPublisherRejectsMalformedAndOversizedResponses", run: TestPublisherRejectsMalformedAndOversizedResponses},
		{name: "TestPublisherRejectsUnsafeTargetBeforeMutation", run: TestPublisherRejectsUnsafeTargetBeforeMutation},
		{name: "TestPublisherReportsConcurrentDifferentTree", run: TestPublisherReportsConcurrentDifferentTree},
		{name: "TestPublisherRequestJSONDefensiveFailures", run: TestPublisherRequestJSONDefensiveFailures},
		{name: "TestPublisherSkipsCommitWhenTreeIsUnchanged", run: TestPublisherSkipsCommitWhenTreeIsUnchanged},
		{name: "TestPublisherUsesFixedOfficialAPIAndDisablesProxy", run: TestPublisherUsesFixedOfficialAPIAndDisablesProxy},
	}

	for _, test := range tests {
		t.Run(test.name, test.run)
	}
}
