// Code generated by scripts/fill-integration-coverage.sh; DO NOT EDIT.
//
// This bridge re-executes the package's existing scenario tests during
// the independent integration-coverage pass without changing production code.
package reporting

import "testing"

func TestIntegrationCoverageBridge(t *testing.T) {
	tests := []struct {
		name string
		run  func(*testing.T)
	}{
		{name: "TestAuditFallbackRejectsInvalidLimit", run: TestAuditFallbackRejectsInvalidLimit},
		{name: "TestAuditHandlerRejectsInvalidCursorAndHidesFailures", run: TestAuditHandlerRejectsInvalidCursorAndHidesFailures},
		{name: "TestAuditHandlerUsesOpaqueKeysetPagination", run: TestAuditHandlerUsesOpaqueKeysetPagination},
		{name: "TestAuditPaginationHelpers", run: TestAuditPaginationHelpers},
		{name: "TestCanonicalCursorOriginValidation", run: TestCanonicalCursorOriginValidation},
		{name: "TestCursorValidationRejectsMalformedPayloads", run: TestCursorValidationRejectsMalformedPayloads},
		{name: "TestExtendedTelemetryJSONAppendsFieldsWithoutReorderingContracts", run: TestExtendedTelemetryJSONAppendsFieldsWithoutReorderingContracts},
		{name: "TestHandlerDoesNotExposeReaderFailures", run: TestHandlerDoesNotExposeReaderFailures},
		{name: "TestHandlerDoesNotExposeSourceDetailFailure", run: TestHandlerDoesNotExposeSourceDetailFailure},
		{name: "TestHandlerHealthAndAuthentication", run: TestHandlerHealthAndAuthentication},
		{name: "TestHandlerRejectsInvalidInputsAndMissingCrawl", run: TestHandlerRejectsInvalidInputsAndMissingCrawl},
		{name: "TestHandlerRejectsInvalidSourceDetailInputs", run: TestHandlerRejectsInvalidSourceDetailInputs},
		{name: "TestHandlerReturnsReportingData", run: TestHandlerReturnsReportingData},
		{name: "TestHandlerReturnsSourceDetail", run: TestHandlerReturnsSourceDetail},
		{name: "TestHandlerReturnsSourceNotFound", run: TestHandlerReturnsSourceNotFound},
		{name: "TestHandlerSourceDetailUsesDefaultLimit", run: TestHandlerSourceDetailUsesDefaultLimit},
		{name: "TestHandlerUsesDefaultLimit", run: TestHandlerUsesDefaultLimit},
		{name: "TestMetricsExposeBoundedOperationalState", run: TestMetricsExposeBoundedOperationalState},
		{name: "TestMetricsExposeDurableLowCardinalityTotals", run: TestMetricsExposeDurableLowCardinalityTotals},
		{name: "TestNewHandlerValidatesDependencies", run: TestNewHandlerValidatesDependencies},
		{name: "TestPageTrimmingAndLimitValidation", run: TestPageTrimmingAndLimitValidation},
		{name: "TestPagedHandlersDoNotExposeReaderFailures", run: TestPagedHandlersDoNotExposeReaderFailures},
		{name: "TestPagedHandlersPreserveArrayBodiesAndExposeNextCursor", run: TestPagedHandlersPreserveArrayBodiesAndExposeNextCursor},
		{name: "TestPagedHandlersRejectInvalidQueries", run: TestPagedHandlersRejectInvalidQueries},
		{name: "TestPagedHandlersRequireAuthentication", run: TestPagedHandlersRequireAuthentication},
		{name: "TestPagedHandlersUseDefaultsAndNoCursorHeader", run: TestPagedHandlersUseDefaultsAndNoCursorHeader},
		{name: "TestPaginationMiddlewarePassesOtherRequestsThrough", run: TestPaginationMiddlewarePassesOtherRequestsThrough},
		{name: "TestReportingAuthorizationUsesFixedLengthDigest", run: TestReportingAuthorizationUsesFixedLengthDigest},
		{name: "TestTypedCursorValidationRejectsWrongShapes", run: TestTypedCursorValidationRejectsWrongShapes},
	}

	for _, test := range tests {
		t.Run(test.name, test.run)
	}
}
